
obstacle_bp_names = [
    "static.prop.trashcan01",
    "static.prop.trashcan02",
    "static.prop.barrel",
    "static.prop.trashcan04",
    "static.prop.trashcan05",
    "static.prop.trashcan03",
    "static.prop.shoppingbag",
    "static.prop.gnome",
    "static.prop.trafficcone01",
    "static.prop.trafficcone02",
    "static.prop.plasticchair",
    "static.prop.creasedbox01",
    "static.prop.trashbag",
    "static.prop.gardenlamp",
    "static.prop.streetbarrier",
    "static.prop.creasedbox02",
    "static.prop.creasedbox03",
    "static.prop.constructioncone",
    "static.prop.box03",
    "static.prop.box01",
    "static.prop.box02",
    "static.prop.bin",
    # "static.prop.streetsign04",
    # "static.prop.shoppingcart"
    # "static.prop.container",
    # "static.prop.glasscontainer",
    # "static.prop.streetsign01",
    # "static.prop.dirtdebris01",
    # "static.prop.dirtdebris03",
    # "static.prop.dirtdebris02",
    # "static.prop.plastictable",
    # "static.prop.shoppingtrolley",
    # "static.prop.plasticbag",
    # "static.prop.wateringcan",
    # "static.prop.streetsign",
    # "static.prop.travelcase",
    # "static.prop.guitarcase",
    # "static.prop.bench01",
    # "static.prop.briefcase",
    # "static.prop.brokentile02",
    # "static.prop.garbage04",
    # "static.prop.maptable",
    # "static.prop.slide",
    # "static.prop.swingcouch",
    # "static.prop.barbeque",
    # "static.prop.streetfountain",
    # "static.prop.plantpot07",
    # "static.prop.atm",
    # "static.prop.busstop",
    # "static.prop.brokentile03",
    # "static.prop.vendingmachine",
    # "static.prop.mailbox",
    # "static.prop.mobile",
    # "static.prop.bike",
    # "static.prop.mesh",
    # "static.prop.plantpot05",
    # "static.prop.advertisement",
    # "static.prop.swing",
    # "static.prop.fountain",
    # "static.prop.clothcontainer",
    # "static.prop.trampoline",
    # "static.prop.plantpot01",
    # "static.prop.purse",
    # "static.prop.garbage02",
    # "static.prop.calibrator",
    # "static.prop.plantpot03",
    # "static.prop.garbage01",
    # "static.prop.plantpot02",
    # "static.prop.ironplank",
    # "static.prop.chainbarrierend",
    # "static.prop.doghouse",
    # "static.prop.kiosk_01",
    # "static.prop.garbage03",
    # "static.prop.garbage05",
    # "static.prop.trafficwarning",
    # "static.prop.garbage06",
    # "static.prop.plantpot06",
    # "static.prop.platformgarbage01",
    # "static.prop.plantpot04",
    # "static.prop.pergola",
    # "static.prop.colacan",
    # "static.prop.table",
    # "static.prop.clothesline",
    # "static.prop.brokentile04",
    # "static.prop.brokentile01",
    # "static.prop.plantpot08",
    # "static.prop.chainbarrier",
    # "static.prop.bench03",
    # "static.prop.motorhelmet",
    # "static.prop.bench02",
]
